name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag stable-diffusion-openvino:$(date +%s)
    - name: Save the Docker image
      run: docker save -O stable-diffusion-openvino.tar stable-diffusion-openvino
      
 
